[project]
name="neutron-cinema"
version="2.0.0a1"
authors=[
    {name="Xiao-Xiao Cai"},
    {name="Ming Tang"},
    {name="Zi-Yi Pan"},
    {name="Ni Yang"},
    {email="cinema-users@outlook.com"},
    ]
maintainers = [
    { name = "Zi-Yi Pan", email = "zypan@ihep.ac.cn" },
]
description="China Spallation Neutron Source Monte Carlo System"
license = "Apache-2.0"
readme = "README.md"
keywords = ["NCyrstal", "Neutron Scattering", "Spectroscopy"]
requires-python = ">=3.8"
classifiers = [
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Physics',
    'Operating System :: POSIX :: Linux',
]
dependencies = [
    "ncrystal",
    "ncrystal-pypluginmgr",
    "ncrystal-plugin-bzscope @ git+https://code.ihep.ac.cn/cinema-developers/ncplugin-bzscope",
    "scipy", "h5py", "mpi4py", "psutil", "tqdm", "gvar", "mcpl-core"
]

[project.optional-dependencies]
viz = [ "pyvista", "matplotlib"]

# [project.scripts]
# my_package_cli = 'my_package.console:run'

[project.urls]
repository = "https://code.ihep.ac.cn/cinema-developers/cinema"
"Bug Tracker" = "https://code.ihep.ac.cn/cinema-developers/cinema/-/issues"
"Paper" = "https://doi.org/10.1016/j.cpc.2023.109004"

[build-system]
requires = [
    "hatchling", 
    "hatch-build-scripts", 
    "requests",
    "ncrystal-core",
    "mcpl-core"
]
build-backend = "hatchling.build"

[project.scripts]
prompt = "Cinema.Prompt.cli.promptcli:main"

[tool.hatch.metadata]
allow-direct-references = true # To make git + magic happen

[[tool.hatch.build.hooks.build-scripts.scripts]]
out_dir = "build"
commands = [
    "python tools/scripts/build_tool/install_cdeps.py > output.txt",
]
artifacts = [
    "output.txt"
]

[tool.hatch.build.targets.wheel]
packages = ["src/python/Cinema"]
exclude = ["src/python/Cinema/PiXiu", "src/python/Cinema/Tak"]
artifacts = [
    "src/python/Cinema/*.so"
]

[tool.hatch.build.targets.wheel.force-include]
"scripts/guide.py" = "Cinema/examples/guide.py"