python:
  - 3.8
  # - 3.9
  # - 3.10
  - 3.11
CONDA_BUILD_SYSROOT:
  # - /opt/MacOSX10.10.sdk        # [osx-64]
c_compiler:
  - gcc
  # - clang
cxx_compiler:
  - gxx
  # - clangxx
c_compiler_version:
  - 9.4.0
  # - 16.0
cxx_compiler_version:
  - 9.4.0
  # - 16.0
target_platform:
  # - osx-64
  # - linux-aarch64
  - linux-64
  # - osx-64
zip_keys:
  - 
    - c_compiler
    - c_compiler_version
    - cxx_compiler
    - cxx_compiler_version
    - target_platform
