#!/bin/bash

USAGE="Usage: $0 -t for unit test"

.  $CINEMAPATH/external/ncrystal/install/setup.sh

BUILDTYPE="release"

while getopts ti:d option
  do
    case "${option}"
    in
      h) echo "$USAGE"
         exit 0;;
      t) TESTFLAG="test";;
      d) echo "Building cinema in the debug mode"
         BUILDTYPE="debug";;
    esac
done


cd $CINEMAPATH/cinemabin
cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ..
make -j

if [ -z ${TESTFLAG} ]; then
  echo "Skipped unittest";
else
  make -j
  ctest -j8
fi
cd -
