#!/usr/bin/env python3

from Cinema.Prompt import Prompt, PromptMPI
from Cinema.Prompt.geo import Volume, Transformation3D
from Cinema.Prompt.solid import Box
from Cinema.Prompt.gun import PythonGun
import numpy as np

class MySim(PromptMPI):
    def __init__(self, seed=4096) -> None:
        super().__init__(seed)

    def makeWorld(self, anyUserParameters=np.zeros(2)):
        scorerCfg_detpsd = "Scorer=PSD;name=NeutronHistMap;xmin=-500;xmax=500;numbin_x=10;ymin=-500;ymax=500;numbin_y=10;ptstate=SURFACE;type=XY"
        scorerCfg_detwl = "Scorer=WlSpectrum; name=detector; min=0.0; max=5; numbin=200"
        matCfg_sample = "physics=ncrystal;nccfg='LiquidHeavyWaterD2O_T293.6K.ncmat';scatter_bias=10;abs_bias=1"

        world = Volume("world", Box(210, 210, 210))
        detector = Volume("Det", Box(400, 400, 0.0001))
        detector.addScorer(scorerCfg_detpsd)
        detector.addScorer(scorerCfg_detwl)

        sample = Volume("sample", Box(20,20,20))
        water = Volume('sbox', Box(2,2,2), matCfg = matCfg_sample)

        for i in range(10):
            sample.placeChild("ssample", water, Transformation3D(0,0,2.2*(i-5.0)), scorerGroup=i)

        world.placeChild("physicalbox", detector, Transformation3D(0., 0., 50), 1)
        world.placeChild("physicalbox2", sample, Transformation3D(-150, 45, 45))
        self.l.setWorld(world)


class MyGun(PythonGun):
    def __init__(self):
        super().__init__()

    def samplePosition(self):
        return 0,0,-209


sim = MySim(seed=1010)
sim.makeWorld()

# set gun
if False: #could be in either old style or the python style
    gunCfg = "gun=SimpleThermalGun;position=0,0,-200;direction=0,0,1"
    sim.setGun(gunCfg)
else:
    gun = MyGun()
    sim.setGun(gun)

# vis or production
if False:
    sim.show(1000)
else:
    sim.simulate(1e6)

wlhist = sim.getScorerHist('Scorer=WlSpectrum; name=detector; min=0.0; max=5; numbin=200', raw=True)
np.allclose(wlhist.getWeight().sum(), 817540.6738638073)
np.allclose(wlhist.getHit().sum(), 201053.0)

if sim.rank==0:
    print(f'total {wlhist.getWeight().sum()} {wlhist.getHit().sum()}')
    wlhist.plot(show=True)

