#!/usr/bin/env python3

from Cinema.Prompt import Launcher, Visualiser
from Cinema.Prompt.geo import UnplacedBox, LogicalVolume, Transformation3D
from Cinema.Prompt.utils import call_python_method


class celsius:
    def __init__(self, degrees):
        self.degrees = degrees

    def farenheit(self):
        return ((self.degrees * 9.0) / 5.0) + 32.0

import ctypes
a = (celsius(100))

res = call_python_method(a, "farenheit")
print(res)





box = UnplacedBox(4,4,4)
b1 = LogicalVolume("box1", box)
b1.matCfg = "physics=ncrystal;nccfg='LiquidHeavyWaterD2O_T293.6K.ncmat';scatter_bias=0.1;abs_bias=0.1"

print(f'bi id {b1.getLogicalID()} ')

world = LogicalVolume("world", UnplacedBox(10, 10, 10))
world.placeChild("physicalbox", b1, Transformation3D(5 , 5, 5, 0,0,0), 1)
world.placeChild("physicalbox", b1, Transformation3D(-5 , -5, -5, 0,0,0))

world.placeChild("physicalbox", LogicalVolume("box2", UnplacedBox(4, 4 , 4), 
                scorerCfg="""Scorer=PSD;name=Monitor2;xmin=-5;xmax=5;
                          numBins_x=20;ymin=-5;ymax=5;numBins_y=20;type=XY"""), Transformation3D(-5 , 5, -5, 0,0,0),10101)

print(f'bi id {b1.getLogicalID()} ')

l = Launcher()
l.setWorld(world)


# l.go(1000)

v= Visualiser()

for i in range(100):
    l.go(1, recordTrj=True, timer=False)
    trj = l.getTrajectory()
    try:
        v.addLine(trj)
    except ValueError:
        # print(trj)
        # print("skip ValueError in File '/Prompt/scripts/prompt', in <module>, v.addLine(trj)")
        pass

v.show()
