#!/bin/bash

USAGE="Usage: $0 -t for unit test"

.  $PTPATH/external/ncrystal/install/setup.sh
while getopts ti:d option
  do
    case "${option}"
    in
      h) echo "$USAGE"
         exit 0;;
      t) TESTFLAG="test";;
    esac
done


cd $PTPATH/promptbin
cmake ..
make -j

if [ -z ${TESTFLAG} ]; then
  echo "Skipped unittest";
else
  make -j test
fi
cd -
