#!/usr/bin/env python3

from  Cinema.Prompt.compoundModel import CompoundModel
import numpy as np
import matplotlib.pyplot as plt
import argparse
from Cinema.Interface import plotStyle
from Cinema.Prompt.centralData import CentralData 
from Cinema.Prompt.utils import nccalNumDensity

plotStyle()

parser = argparse.ArgumentParser()

parser.add_argument('cfg', metavar='N', type=str, nargs='+', help='Prompt materil config')

parser.add_argument('-c', '--switchingenergy', action='store',  nargs='+', type=float, default=10.,
                    dest='switchingenergy', help='model switching energy')

import openmc


cdata=CentralData()
cdata.setEnableGidi(True)

args=parser.parse_args()
print(args.switchingenergy)



ekin = np.logspace(-5, np.log10(20e6), 100000)

for cfg in args.cfg:
    m1 = openmc.Material.from_ncrystal(cfg)
    m1.name = cfg
    fig = openmc.plot_xs({m1:['total']})
    
    numberdensity = nccalNumDensity(cfg)
    print('number density', )    

    for sen in args.switchingenergy:
        cdata.setGidiThreshold(sen)
        comp = CompoundModel(cfg)
        xs = np.zeros_like(ekin)
        for i in range(ekin.size):
            xs[i] = comp.xs(ekin[i])        
        macroxs = numberdensity*xs*1e-21
        plt.loglog(ekin, macroxs, label=cfg+', switching@'+str(sen))

plt.legend(loc=0)
plt.grid('both')
plt.show()